server:
  port: 1119
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: E:\最新2019黑马java全套\最新2019java黑马全（idea）\11-乐优商城\leyou\day17-授权中心\tmp\rsa\rsa.pub # 公钥地址
    priKeyPath: E:\最新2019黑马java全套\最新2019java黑马全（idea）\11-乐优商城\leyou\day17-授权中心\tmp\rsa\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 30 # cookie生存时间