server:
  port: 1200
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.254.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: E:\最新2019黑马java全套\最新2019java黑马全（idea）\11-乐优商城\leyou\day17-授权中心\tmp\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称